// <auto-generated />
using System;
using BloodLineAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodLineAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430001411_AddDeviceTokenTable")]
    partial class AddDeviceTokenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BadgeDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BadgeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BadgeNameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BadgeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BonusPoints")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeKey")
                        .IsUnique();

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6ee9496-e7fb-43c3-8275-ec5f35cf01a1"),
                            BadgeDescription = "Awarded for completing your first donation.",
                            BadgeKey = "giver",
                            BadgeName = "Giver",
                            BadgeNameAr = "المعطي",
                            BadgeType = "Milestone",
                            BonusPoints = 50,
                            IconUrl = "badges/giver.png"
                        },
                        new
                        {
                            Id = new Guid("cc39fc72-7f5f-4d17-9bfd-9a2f3f5b8db1"),
                            BadgeDescription = "Awarded after 3 completed donations.",
                            BadgeKey = "helper",
                            BadgeName = "Helper",
                            BadgeNameAr = "المساعد",
                            BadgeType = "Milestone",
                            BonusPoints = 75,
                            IconUrl = "badges/helper.png"
                        },
                        new
                        {
                            Id = new Guid("89e198c4-d715-4cf6-a85f-7696159f423a"),
                            BadgeDescription = "Awarded after 5 completed donations.",
                            BadgeKey = "hero",
                            BadgeName = "Hero",
                            BadgeNameAr = "البطل",
                            BadgeType = "Milestone",
                            BonusPoints = 100,
                            IconUrl = "badges/hero.png"
                        },
                        new
                        {
                            Id = new Guid("e3f8c38b-3858-45f0-b571-c7ec736dbfee"),
                            BadgeDescription = "Awarded after 10 completed donations.",
                            BadgeKey = "life_saver",
                            BadgeName = "Life Saver",
                            BadgeNameAr = "منقذ الحياة",
                            BadgeType = "Milestone",
                            BonusPoints = 150,
                            IconUrl = "badges/life_saver.png"
                        },
                        new
                        {
                            Id = new Guid("c80d19d2-63d9-4fb6-bf77-fa8f253f50b4"),
                            BadgeDescription = "Awarded after 20 completed donations.",
                            BadgeKey = "monqez",
                            BadgeName = "Monqez",
                            BadgeNameAr = "منقذ",
                            BadgeType = "Milestone",
                            BonusPoints = 300,
                            IconUrl = "badges/monqez.png"
                        },
                        new
                        {
                            Id = new Guid("2ef1880e-ca8b-4383-8584-3b31f1fb9448"),
                            BadgeDescription = "Awarded for the first emergency donation.",
                            BadgeKey = "responder",
                            BadgeName = "Responder",
                            BadgeNameAr = "المستجيب",
                            BadgeType = "Action",
                            BonusPoints = 100,
                            IconUrl = "badges/responder.png"
                        },
                        new
                        {
                            Id = new Guid("db1d6774-bf5f-4fdd-aea3-b3865e6a546d"),
                            BadgeDescription = "Awarded for donors with rare blood type O- or AB-.",
                            BadgeKey = "golden_blood",
                            BadgeName = "Golden Blood",
                            BadgeNameAr = "الدم الذهبي",
                            BadgeType = "Action",
                            BonusPoints = 100,
                            IconUrl = "badges/golden_blood.png"
                        },
                        new
                        {
                            Id = new Guid("7db611c5-b017-48d3-84fb-2273d61938df"),
                            BadgeDescription = "Awarded after sharing 20 urgent requests.",
                            BadgeKey = "ambassador",
                            BadgeName = "Ambassador",
                            BadgeNameAr = "السفير",
                            BadgeType = "Action",
                            BonusPoints = 80,
                            IconUrl = "badges/ambassador.png"
                        },
                        new
                        {
                            Id = new Guid("e98fa758-1395-4ca1-a17c-51b965ef8f77"),
                            BadgeDescription = "Awarded for donating after midnight.",
                            BadgeKey = "night_owl",
                            BadgeName = "Night Owl",
                            BadgeNameAr = "بومة الليل",
                            BadgeType = "Action",
                            BonusPoints = 60,
                            IconUrl = "badges/night_owl.png"
                        });
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.BloodEntities.BloodBag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("BloodTypeId")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("CollectedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DonationAppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Volume")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.HasIndex("CollectedByStaffId");

                    b.HasIndex("DonationAppointmentId")
                        .IsUnique()
                        .HasFilter("[DonationAppointmentId] IS NOT NULL");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("BloodBags");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.BloodEntities.BloodComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodBagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Volume")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("BloodBagId");

                    b.ToTable("BloodComponents");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.BloodEntities.BloodTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodBagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HepatitisBResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HepatitisResult")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HivResult")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsSafe")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestFileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TestedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BloodBagId");

                    b.HasIndex("TestedByStaffId");

                    b.ToTable("BloodTestResults");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.BloodEntities.BloodType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("BloodGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RhFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroupName", "RhFactor")
                        .IsUnique();

                    b.ToTable("BloodTypes");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            BloodGroupName = "A",
                            RhFactor = "Positive"
                        },
                        new
                        {
                            Id = (byte)2,
                            BloodGroupName = "A",
                            RhFactor = "Negative"
                        },
                        new
                        {
                            Id = (byte)3,
                            BloodGroupName = "B",
                            RhFactor = "Positive"
                        },
                        new
                        {
                            Id = (byte)4,
                            BloodGroupName = "B",
                            RhFactor = "Negative"
                        },
                        new
                        {
                            Id = (byte)5,
                            BloodGroupName = "AB",
                            RhFactor = "Positive"
                        },
                        new
                        {
                            Id = (byte)6,
                            BloodGroupName = "AB",
                            RhFactor = "Negative"
                        },
                        new
                        {
                            Id = (byte)7,
                            BloodGroupName = "O",
                            RhFactor = "Positive"
                        },
                        new
                        {
                            Id = (byte)8,
                            BloodGroupName = "O",
                            RhFactor = "Negative"
                        });
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DiscardRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorizedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodBagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiscardDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizedByStaffId");

                    b.HasIndex("BloodBagId")
                        .IsUnique();

                    b.ToTable("DiscardRecords");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.CenterExclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<TimeSpan?>("SpecialClosingTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("SpecialOpeningTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CenterId", "Date")
                        .IsUnique();

                    b.ToTable("CenterExclusions");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.DonationAppointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonationCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid?>("HealthPreScreeningId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DonationCenterId");

                    b.HasIndex("DonorId");

                    b.HasIndex("HealthPreScreeningId");

                    b.ToTable("DonationAppointments");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.DonationCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressDetails")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CenterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MaxDonorsPerSlot")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SlotDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupportedDonationTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DonationCenters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5b4d5b7-eaf8-4a92-8b0a-2fc73f6cc3d1"),
                            AddressDetails = "Beni Suef Main Branch",
                            CenterType = "MainBranch",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionText = "Main branch in Beni Suef.",
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            Latitude = 29.042005899999999,
                            Location = "Beni Suef",
                            Longitude = 31.118414000000001,
                            MaxDonorsPerSlot = 10,
                            Name = "Beni Suef Main Branch",
                            SlotDurationMinutes = 15,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            Status = "Active",
                            SupportedDonationTypes = "WholeBlood,Plasma,Platelets"
                        });
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.DonationRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonationAppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FeedbackText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StarScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonationAppointmentId")
                        .IsUnique();

                    b.HasIndex("DonorId");

                    b.ToTable("DonationRatings");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.HealthPreScreening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasAnyDisqualifyingCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBeenThreeToFourMonthsSinceLastDonation")
                        .HasColumnType("bit");

                    b.Property<bool>("HasChronicIllnessAffectingBloodDonation")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCurrentFeverInfectionOrSevereCold")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDentalProcedureInPastWeek")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRecentSurgeryInPast6Months")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRecentTattooOrPiercingInPast6Months")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTakingBloodThinnersOrCriticalMedication")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScreenedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.ToTable("HealthPreScreenings");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.OpeningHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxDonorsPerSlot")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CenterId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("OpeningHours");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b14eefa-72d9-4f83-aad4-6d4e90ca8e10"),
                            CenterId = new Guid("b5b4d5b7-eaf8-4a92-8b0a-2fc73f6cc3d1"),
                            ClosingTime = new TimeSpan(0, 21, 0, 0, 0),
                            DayOfWeek = 0,
                            IsClosed = false,
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("7f98f6f7-9556-4fbb-a457-e15457d0656f"),
                            CenterId = new Guid("b5b4d5b7-eaf8-4a92-8b0a-2fc73f6cc3d1"),
                            ClosingTime = new TimeSpan(0, 21, 0, 0, 0),
                            DayOfWeek = 1,
                            IsClosed = false,
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("9da3ab38-757b-4b96-80a5-3e84f917f4fe"),
                            CenterId = new Guid("b5b4d5b7-eaf8-4a92-8b0a-2fc73f6cc3d1"),
                            ClosingTime = new TimeSpan(0, 21, 0, 0, 0),
                            DayOfWeek = 2,
                            IsClosed = false,
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("0eb9fceb-4f4f-48b5-80c5-63f9da73b763"),
                            CenterId = new Guid("b5b4d5b7-eaf8-4a92-8b0a-2fc73f6cc3d1"),
                            ClosingTime = new TimeSpan(0, 21, 0, 0, 0),
                            DayOfWeek = 3,
                            IsClosed = false,
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("f7ff2d1c-b95a-4f08-806d-9bf8f5f1a036"),
                            CenterId = new Guid("b5b4d5b7-eaf8-4a92-8b0a-2fc73f6cc3d1"),
                            ClosingTime = new TimeSpan(0, 21, 0, 0, 0),
                            DayOfWeek = 4,
                            IsClosed = false,
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("2dc3fd35-a567-437f-a53f-c833fddfa0f7"),
                            CenterId = new Guid("b5b4d5b7-eaf8-4a92-8b0a-2fc73f6cc3d1"),
                            ClosingTime = new TimeSpan(0, 21, 0, 0, 0),
                            DayOfWeek = 5,
                            IsClosed = false,
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3f9ef858-2962-47d5-95f9-c7e3f2eaeb58"),
                            CenterId = new Guid("b5b4d5b7-eaf8-4a92-8b0a-2fc73f6cc3d1"),
                            ClosingTime = new TimeSpan(0, 21, 0, 0, 0),
                            DayOfWeek = 6,
                            IsClosed = false,
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Donor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("AllowLeaderboardVisibility")
                        .HasColumnType("bit");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("BloodTypeId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FourthName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRegistrationCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastDonationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthlyPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalDonationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonorBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EarnedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("DonorId");

                    b.ToTable("DonorBadges");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodBagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExecutedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodBagId");

                    b.HasIndex("ExecutedByStaffId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.MedicalScreening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BloodPressure")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("ChronicDiseases")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("HemoglobinLevel")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsAllergic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PerformedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ScreeningDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("PerformedByStaffId");

                    b.ToTable("MedicalScreenings");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SentVia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MonthKey")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonorId", "ActionType");

                    b.HasIndex("DonorId", "MonthKey");

                    b.HasIndex("MonthKey", "Points");

                    b.ToTable("PointTransactions");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActiveEmployee")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeIdentifier")
                        .IsUnique();

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.UrgentBloodAppeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BroadcastDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentBagsCollected")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetBagsNeeded")
                        .HasColumnType("int");

                    b.Property<string>("TargetDistrict")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByStaffId");

                    b.ToTable("UrgentBloodAppeals");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationOtpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegistrationOtpExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("BloodTypeUrgentBloodAppeal", b =>
                {
                    b.Property<byte>("TargetedBloodTypesId")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UrgentBloodAppealsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TargetedBloodTypesId", "UrgentBloodAppealsId");

                    b.HasIndex("UrgentBloodAppealsId");

                    b.ToTable("BloodTypeUrgentBloodAppeal");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.BloodEntities.BloodBag", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.BloodEntities.BloodType", "BloodType")
                        .WithMany("BloodBags")
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.Staff", "CollectedByStaff")
                        .WithMany("CollectedBloodBags")
                        .HasForeignKey("CollectedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.DonationEntities.DonationAppointment", "DonationAppointment")
                        .WithOne("BloodBag")
                        .HasForeignKey("BloodLineAPI.Domain.Entities.BloodEntities.BloodBag", "DonationAppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BloodType");

                    b.Navigation("CollectedByStaff");

                    b.Navigation("DonationAppointment");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.BloodEntities.BloodComponent", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.BloodEntities.BloodBag", "BloodBag")
                        .WithMany("BloodComponents")
                        .HasForeignKey("BloodBagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodBag");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.BloodEntities.BloodTestResult", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.BloodEntities.BloodBag", "BloodBag")
                        .WithMany("BloodTestResults")
                        .HasForeignKey("BloodBagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.Staff", "TestedByStaff")
                        .WithMany("BloodTestResults")
                        .HasForeignKey("TestedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodBag");

                    b.Navigation("TestedByStaff");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DeviceToken", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Users.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DiscardRecord", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Staff", "AuthorizedByStaff")
                        .WithMany("AuthorizedDiscardRecords")
                        .HasForeignKey("AuthorizedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.BloodEntities.BloodBag", "BloodBag")
                        .WithOne("DiscardRecord")
                        .HasForeignKey("BloodLineAPI.Domain.Entities.DiscardRecord", "BloodBagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorizedByStaff");

                    b.Navigation("BloodBag");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.CenterExclusion", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.DonationEntities.DonationCenter", "Center")
                        .WithMany("CenterExclusions")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.DonationAppointment", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.DonationEntities.DonationCenter", "DonationCenter")
                        .WithMany("DonationAppointments")
                        .HasForeignKey("DonationCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.Donor", "Donor")
                        .WithMany("DonationAppointments")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.DonationEntities.HealthPreScreening", "HealthPreScreening")
                        .WithMany()
                        .HasForeignKey("HealthPreScreeningId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DonationCenter");

                    b.Navigation("Donor");

                    b.Navigation("HealthPreScreening");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.DonationRating", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.DonationEntities.DonationAppointment", "DonationAppointment")
                        .WithOne("DonationRating")
                        .HasForeignKey("BloodLineAPI.Domain.Entities.DonationEntities.DonationRating", "DonationAppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.Donor", "Donor")
                        .WithMany("DonationRatings")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonationAppointment");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.HealthPreScreening", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Donor", "Donor")
                        .WithMany("HealthPreScreenings")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.OpeningHours", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.DonationEntities.DonationCenter", "Center")
                        .WithMany("OpeningHours")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Donor", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.BloodEntities.BloodType", "BloodType")
                        .WithMany("Donors")
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BloodLineAPI.Domain.Entities.Users.User", "User")
                        .WithOne("Donor")
                        .HasForeignKey("BloodLineAPI.Domain.Entities.Donor", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonorBadge", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Badge", "Badge")
                        .WithMany("DonorBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.Donor", "Donor")
                        .WithMany("DonorBadges")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.BloodEntities.BloodBag", "BloodBag")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("BloodBagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.Staff", "ExecutedByStaff")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ExecutedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodBag");

                    b.Navigation("ExecutedByStaff");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.MedicalScreening", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Donor", "Donor")
                        .WithMany("MedicalScreenings")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.Staff", "PerformedByStaff")
                        .WithMany("MedicalScreenings")
                        .HasForeignKey("PerformedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("PerformedByStaff");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Notification", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Users.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.PointTransaction", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Donor", "Donor")
                        .WithMany("PointTransactions")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Staff", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Users.User", "User")
                        .WithOne("Staff")
                        .HasForeignKey("BloodLineAPI.Domain.Entities.Staff", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.UrgentBloodAppeal", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Staff", "CreatedByStaff")
                        .WithMany("UrgentBloodAppeals")
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByStaff");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Users.UserRole", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodTypeUrgentBloodAppeal", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.BloodEntities.BloodType", null)
                        .WithMany()
                        .HasForeignKey("TargetedBloodTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodLineAPI.Domain.Entities.UrgentBloodAppeal", null)
                        .WithMany()
                        .HasForeignKey("UrgentBloodAppealsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BloodLineAPI.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Badge", b =>
                {
                    b.Navigation("DonorBadges");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.BloodEntities.BloodBag", b =>
                {
                    b.Navigation("BloodComponents");

                    b.Navigation("BloodTestResults");

                    b.Navigation("DiscardRecord");

                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.BloodEntities.BloodType", b =>
                {
                    b.Navigation("BloodBags");

                    b.Navigation("Donors");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.DonationAppointment", b =>
                {
                    b.Navigation("BloodBag");

                    b.Navigation("DonationRating");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.DonationEntities.DonationCenter", b =>
                {
                    b.Navigation("CenterExclusions");

                    b.Navigation("DonationAppointments");

                    b.Navigation("OpeningHours");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Donor", b =>
                {
                    b.Navigation("DonationAppointments");

                    b.Navigation("DonationRatings");

                    b.Navigation("DonorBadges");

                    b.Navigation("HealthPreScreenings");

                    b.Navigation("MedicalScreenings");

                    b.Navigation("PointTransactions");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Staff", b =>
                {
                    b.Navigation("AuthorizedDiscardRecords");

                    b.Navigation("BloodTestResults");

                    b.Navigation("CollectedBloodBags");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("MedicalScreenings");

                    b.Navigation("UrgentBloodAppeals");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Users.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BloodLineAPI.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("DeviceTokens");

                    b.Navigation("Donor");

                    b.Navigation("Notifications");

                    b.Navigation("Staff");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
